name: bakery
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - numpy=1.23
  - altair
  - anyio
  - argon2-cffi
  - arrow
  - asttokens
  - async-lru
  - attrs
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - azure-core-cpp
  - azure-identity-cpp
  - azure-storage-blobs-cpp
  - azure-storage-common-cpp
  - azure-storage-files-datalake-cpp
  - babel
  - beautifulsoup4
  - bleach
  - blinker
  - brotli
  - bzip2
  - c-ares
  - ca-certificates
  - cached-property
  - cachetools
  - certifi
  - cffi
  - charset-normalizer
  - click
  - comm
  - contourpy
  - cycler
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - exceptiongroup
  - executing
  - fonttools
  - fqdn
  - freetype
  - gflags
  - gitdb
  - gitpython
  - glog
  - h11
  - h2
  - hpack
  - httpcore
  - httpx
  - hyperframe
  - icu
  - idna
  - importlib-metadata
  - importlib-resources
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - isoduration
  - jedi
  - jinja2
  - json5
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - jsonschema-with-format-nongpl
  - jupyter-lsp
  - jupyter_client
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - keyutils
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libabseil
  - libarrow
  - libarrow-acero
  - libarrow-dataset
  - libarrow-substrait
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcrc32c
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libevent
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libgomp
  - libgoogle-cloud
  - libgoogle-cloud-storage
  - libgrpc
  - libiconv
  - libjpeg-turbo
  - liblapack
  - libnghttp2
  - libnsl
  - libopenblas
  - libparquet
  - libpng
  - libprotobuf
  - libre2-11
  - libsodium
  - libsqlite
  - libssh2
  - libstdcxx-ng
  - libthrift
  - libtiff
  - libutf8proc
  - libuuid
  - libwebp-base
  - libxcb
  - libxcrypt
  - libxml2
  - libzlib
  - lz4-c
  - markdown-it-py
  - markupsafe
  - matplotlib-base
  - matplotlib-inline
  - mdurl
  - mistune
  - munkres
  - nbclient
  - nbconvert-core
  - nbformat
  - ncurses
  - nest-asyncio
  - notebook
  - notebook-shim
  - openjpeg
  - openssl
  - orc
  - overrides
  - packaging
  - pandas
  - pandocfilters
  - parso
  - patsy
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pkgutil-resolve-name
  - platformdirs
  - plotly
  - prometheus_client
  - prompt-toolkit
  - protobuf
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pyarrow
  - pyarrow-core
  - pycparser
  - pydeck
  - pygments
  - pyparsing
  - pysocks
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python-tzdata
  - pytz
  - pyyaml
  - pyzmq
  - qhull
  - re2
  - readline
  - referencing
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rich
  - rpds-py
  - s2n
  - scipy
  - seaborn
  - seaborn-base
  - send2trash
  - setuptools
  - six
  - smmap
  - snappy
  - sniffio
  - soupsieve
  - stack_data
  - statsmodels
  - streamlit
  - tenacity
  - terminado
  - tinycss2
  - tk
  - toml
  - tomli
  - toolz
  - tornado
  - traitlets
  - types-python-dateutil
  - typing-extensions
  - typing_utils
  - tzdata
  - tzlocal
  - unicodedata2
  - uri-template
  - urllib3
  - validators
  - watchdog
  - wcwidth
  - webcolors
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - yaml
  - zeromq
  - zipp
  - zstandard
  - zstd
